### ISSUE TITLE
typescript 类型获取错误

### ISSUE THREAD

**Issue by vxhly** [moefyit/moefy-canvas#83]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/17906558/171638452-2f17fe8e-d22b-4e60-9447-9a1298237103.png">

**Comment by SigureMo** [comment]
唔，貌似是 vite-plugin-dts 的问题？我才发现打包后获取不到类型信息，唔之后我再试试配置下，如果不行试试换 unbuild 和 tsup 打包试试吧～

**Comment by SigureMo** [comment]
唔，发现 vite-plugin-dts@1.0.0 莫名其妙更改了默认行为，重新配置后好了

<img width="528" alt="image" src="https://user-images.githubusercontent.com/38436475/172065991-0fb7251c-ebfc-4dfc-a5d6-a1db4f55e414.png">

已发布 0.3.3，可以更新一下试试～
